# Generated by Django 5.0.4 on 2024-06-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('crew_size', models.IntegerField()),
                ('time_frame', models.CharField(max_length=255)),
                ('landmarks', models.CharField(blank=True, max_length=255, null=True)),
                ('special_equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('report', models.TextField()),
            ],
        ),
    ]
