# Generated by Django 5.0.4 on 2024-06-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_project_crew_requirements_project_logistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('crew_size', models.IntegerField()),
                ('time_frame', models.CharField(max_length=255)),
                ('landmarks', models.CharField(blank=True, max_length=255, null=True)),
                ('special_equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('report', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_details', to='project.project')),
            ],
        ),
    ]
