# Generated by Django 5.0.4 on 2024-06-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliance',
            old_name='locations',
            new_name='location',
        ),
    ]
