# Generated by Django 5.0.4 on 2024-06-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(default='Unknown', max_length=255)),
                ('model', models.CharField(default='Unknown', max_length=255)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('frame_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('sensor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('connectivity', models.JSONField(blank=True, null=True)),
                ('audio_input', models.JSONField(blank=True, null=True)),
                ('battery_life', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('accessories', models.JSONField(blank=True, null=True)),
                ('rental_price_per_day', models.CharField(blank=True, max_length=50, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('height_range', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('inputs', models.JSONField(blank=True, null=True)),
                ('output', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution_support', models.CharField(blank=True, max_length=50, null=True)),
                ('control_interface', models.CharField(blank=True, max_length=50, null=True)),
                ('wireless', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency_range', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency_response', models.CharField(blank=True, max_length=50, null=True)),
                ('transmitter_battery_life', models.CharField(blank=True, max_length=50, null=True)),
                ('transducer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('directionality', models.CharField(blank=True, max_length=50, null=True)),
                ('channels', models.CharField(blank=True, max_length=50, null=True)),
                ('effects', models.CharField(blank=True, max_length=50, null=True)),
                ('speaker_type', models.CharField(blank=True, max_length=50, null=True)),
                ('power_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('light_type', models.CharField(blank=True, max_length=50, null=True)),
                ('power', models.CharField(blank=True, max_length=50, null=True)),
                ('color_temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('brightness', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('shape', models.CharField(blank=True, max_length=50, null=True)),
                ('diffuser_type', models.CharField(blank=True, max_length=50, null=True)),
                ('mount_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sections', models.CharField(blank=True, max_length=50, null=True)),
                ('features', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('cable_type', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('bandwidth', models.CharField(blank=True, max_length=50, null=True)),
                ('range', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=50, null=True)),
                ('compatibility', models.CharField(blank=True, max_length=50, null=True)),
                ('processor', models.CharField(blank=True, max_length=50, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('power_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_runtime', models.CharField(blank=True, max_length=50, null=True)),
                ('graphics_card', models.CharField(blank=True, max_length=50, null=True)),
                ('license_type', models.CharField(blank=True, max_length=50, null=True)),
                ('media_support', models.CharField(blank=True, max_length=50, null=True)),
                ('interface', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('load_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Specification_required', models.TextField(default='')),
                ('location', models.CharField(max_length=50)),
                ('number_needed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_because', models.TextField(default='Did not store the field')),
            ],
        ),
    ]
