# Generated by Django 5.0.6 on 2024-06-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_rename_name_equipmentrequirement_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentrequirement',
            old_name='model',
            new_name='type',
        ),
    ]
