# Generated by Django 5.0.6 on 2024-06-25 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_project_compliance_report_project_crew_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('driving_licence', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_report_model', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('sensitive', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_report_model', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_report_model', to='project.project')),
                ('crew_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.crewreport')),
                ('equipment_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.equipmentreport')),
            ],
        ),
    ]
