# Generated by Django 5.0.4 on 2024-06-20 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectculture',
            name='culture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='culture.culture'),
        ),
        migrations.AddField(
            model_name='projectculture',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
