# Generated by Django 5.0.4 on 2024-06-20 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_projectculture_culture_projectculture_project'),
        ('project', '0002_project_compliance_report_project_crew_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectculture',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.culture'),
        ),
        migrations.AlterField(
            model_name='projectculture',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
