# Generated by Django 5.0.4 on 2024-06-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flights_details', models.JSONField()),
                ('hotel_details', models.JSONField()),
                ('taxi_details', models.JSONField()),
            ],
        ),
    ]
