# Generated by Django 5.0.4 on 2024-06-20 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_logistics_project'),
        ('project', '0002_project_compliance_report_project_crew_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_set', to='project.project'),
        ),
    ]
