# Generated by Django 5.0.6 on 2024-06-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userid', models.EmailField(max_length=254, unique=True)),
                ('crewType', models.CharField(max_length=50)),
                ('roleJobTitle', models.CharField(max_length=50)),
                ('services', models.JSONField()),
                ('tags', models.JSONField()),
                ('expertise', models.JSONField()),
                ('yoe', models.IntegerField()),
                ('minRatePerDay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maxRatePerDay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('project_detail_from_customer', models.TextField()),
                ('detailed_desc', models.TextField()),
                ('roleJobTitles', models.JSONField()),
                ('crew_requirements', models.JSONField()),
                ('queries', models.JSONField()),
                ('selected_crews', models.JSONField()),
            ],
        ),
    ]
