# Generated by Django 5.0.4 on 2024-06-19 08:19


import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.URLField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('userid', models.EmailField(max_length=254, unique=True)),
                ('crewType', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('services', models.JSONField()),
                ('tags', models.JSONField()),
                ('expertise', models.JSONField()),
                ('yoe', models.IntegerField()),
                ('minRatePerDay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maxRatePerDay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('next_available_date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrewRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('number_needed', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_requirements_set', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_because', models.TextField(default='Did not store the field')),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.crewmember')),
                ('crew_requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.crewrequirement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_crews_set', to='project.project')),
            ],
        ),
    ]
