# Generated by Django 5.0.6 on 2024-06-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_rename_rolejobtitle_crewmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedcrew',
            name='preferred_because',
            field=models.TextField(default='Did not store the field'),
        ),
    ]
