# Generated by Django 5.0.6 on 2024-06-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='profile_pic',
            field=models.URLField(blank=True),
        ),
    ]
