# Generated by Django 5.0.6 on 2024-06-19 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedcrew',
            name='crew_requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_crews', to='crew.crewrequirement'),
        ),
    ]
