# Generated by Django 5.0.4 on 2024-06-20 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_crewrequirement_project_selectedcrew_crew_member_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewrequirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_requirements_set', to='project.project'),
        ),
        migrations.AlterField(
            model_name='selectedcrew',
            name='crew_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.crewmember'),
        ),
        migrations.AlterField(
            model_name='selectedcrew',
            name='crew_requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_crews', to='crew.crewrequirement'),
        ),
        migrations.AlterField(
            model_name='selectedcrew',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_crews_set', to='project.project'),
        ),
    ]
