# Generated by Django 5.0.6 on 2024-06-19 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0001_initial'),
        ('culture', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('budget', models.IntegerField()),
                ('description', models.TextField()),
                ('additional_details', models.TextField()),
                ('location_details', models.JSONField()),
                ('ai_suggestions', models.BooleanField()),
                ('crew_requirements', models.ManyToManyField(related_name='projects_set', to='crew.crewrequirement')),
                ('logistics', models.ManyToManyField(related_name='projects_set', to='logistics.logistics')),
                ('project_cultures', models.ManyToManyField(related_name='projects_set', through='culture.ProjectCulture', to='culture.culture')),
                ('selected_crews', models.ManyToManyField(related_name='projects_set', to='crew.selectedcrew')),
            ],
        ),
    ]
