<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-19 17:03
=======
# Generated by Django 5.0.4 on 2024-06-19 08:18
>>>>>>> 9712475685cb99315246a3fffa5e6ed5573c7031

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('crew', '0001_initial'),
        ('equipment', '0001_initial'),
=======
>>>>>>> 9712475685cb99315246a3fffa5e6ed5573c7031
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('budget', models.IntegerField()),
                ('description', models.TextField()),
                ('additional_details', models.TextField()),
                ('location_details', models.JSONField()),
                ('ai_suggestions', models.BooleanField()),
<<<<<<< HEAD
                ('crew_requirements', models.ManyToManyField(related_name='projects_set', to='crew.crewrequirement')),
                ('equipment_requirements', models.ManyToManyField(related_name='projects_set_equipment1', to='equipment.equipmentrequirement')),
                ('selected_crews', models.ManyToManyField(related_name='projects_set', to='crew.selectedcrew')),
                ('selected_equipments', models.ManyToManyField(related_name='projects_set_equipment2', to='equipment.selectedequipments')),
=======
>>>>>>> 9712475685cb99315246a3fffa5e6ed5573c7031
            ],
        ),
    ]
