# Generated by Django 5.0.4 on 2024-06-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_compliance_project'),
        ('crew', '0003_alter_crewrequirement_project_and_more'),
        ('culture', '0003_alter_projectculture_culture_and_more'),
        ('equipment', '0003_alter_equipmentrequirement_project_and_more'),
        ('logistics', '0003_alter_logistics_project'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='compliance_report',
            field=models.ManyToManyField(related_name='projects_set', to='compliance.compliance'),
        ),
        migrations.AddField(
            model_name='project',
            name='crew_requirements',
            field=models.ManyToManyField(related_name='projects_set', to='crew.crewrequirement'),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_requirements',
            field=models.ManyToManyField(related_name='projects_set', to='equipment.equipmentrequirement'),
        ),
        migrations.AddField(
            model_name='project',
            name='logistics',
            field=models.ManyToManyField(related_name='projects_set', to='logistics.logistics'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_cultures',
            field=models.ManyToManyField(related_name='projects_set', through='culture.ProjectCulture', to='culture.culture'),
        ),
        migrations.AddField(
            model_name='project',
            name='selected_crews',
            field=models.ManyToManyField(related_name='projects_set', to='crew.selectedcrew'),
        ),
        migrations.AddField(
            model_name='project',
            name='selected_equipments',
            field=models.ManyToManyField(related_name='projects_set', to='equipment.selectedequipments'),
        ),
    ]
