# Generated by Django 5.0.4 on 2024-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
        ('culture', '0001_initial'),
        ('logistics', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='crew_requirements',
            field=models.ManyToManyField(related_name='projects_set', to='crew.crewrequirement'),
        ),
        migrations.AddField(
            model_name='project',
            name='logistics',
            field=models.ManyToManyField(related_name='projects_set', to='logistics.logistics'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_cultures',
            field=models.ManyToManyField(related_name='projects_set', through='culture.ProjectCulture', to='culture.culture'),
        ),
        migrations.AddField(
            model_name='project',
            name='selected_crews',
            field=models.ManyToManyField(related_name='projects_set', to='crew.selectedcrew'),
        ),
    ]
