# Generated by Django 5.0.4 on 2024-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_cultures',
            field=models.ManyToManyField(related_name='projects', through='culture.ProjectCulture', to='culture.culture'),
        ),
    ]
