# Generated by Django 5.0.4 on 2024-06-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('project', '0002_project_crew_requirements_project_logistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='compliance_report',
            field=models.ManyToManyField(related_name='projects_set', to='compliance.compliance'),
        ),
    ]
