# Generated by Django 5.0.4 on 2024-06-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
        ('logistics', '0001_initial'),
        ('project', '0002_project_project_cultures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='locations',
            new_name='location_details',
        ),
        migrations.AddField(
            model_name='project',
            name='logistics',
            field=models.ManyToManyField(related_name='projects_set', to='logistics.logistics'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_cultures',
            field=models.ManyToManyField(related_name='projects_set', through='culture.ProjectCulture', to='culture.culture'),
        ),
    ]
