# Generated by Django 5.0.6 on 2024-06-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_compliance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='INITIATED', max_length=255),
        ),
    ]
